extends: default

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '*.yixe'
  - '.yamllint'

rules:
  braces:
    forbid: false
    min-spaces-inside: 1
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  brackets:
    forbid: false
    min-spaces-inside: 1
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  document-start:
    present: false
  document-end:
    present: false
  line-length: disable
